import { z } from "zod";

export const photoSubmissionSchema = z.object({
  // Section 1: Basic Franchise Details
  fullName: z.string().min(1, "Full name is required"),
  franchiseDistrict: z.string().min(1, "Franchise district is required"),
  officeAddress: z.string().min(1, "Office address is required"),
  brandingCompletionDate: z.date({
    required_error: "Branding completion date is required",
  }),

  // Section 2: Photo Uploads
  frontViewPhoto: z.string().optional(),
  receptionAreaPhoto: z.string().optional(),
  workstationsPhoto: z.string().optional(),
  meetingSpacePhoto: z.string().optional(),
  brandingElements: z.array(z.string()).optional(),
  teamPhoto: z.string().optional(),

  // Section 3: Confirmation
  brandingAsPerChecklist: z.enum(["yes", "no"], {
    required_error: "Please confirm if branding was done as per checklist",
  }),
  additionalNotes: z.string().optional(),
  declaration: z.boolean().refine((val) => val === true, {
    message: "You must accept the declaration",
  }),
});

export type PhotoSubmissionFormData = z.infer<typeof photoSubmissionSchema>;

export const franchiseDistricts = [
  "Surat",
  "Chennai", 
  "Palakkad",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivli",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubballi-Dharwad",
  "Tiruchirappalli",
  "Bareilly",
  "Mysore",
  "Tiruppur",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira-Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Guntur",
  "Bikaner",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai Nagar",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Nellore",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Akola",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli-Miraj & Kupwad",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala"
];